language: python

env:
  global:
    DATABASE_URL="dbname='fastfoodfast' host='localhost' port='5432' user='postgres' password='1234'"
    DATABASE_TEST_URL="dbname='fastfoodtest' host='localhost' port='5432' user='postgres' password='1234'"
    CONFIG_TYPE="testing"

python: 
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - psql -c 'CREATE DATABASE fastfoodtest' -U postgres
  - psql -c 'CREATE DATABASE fastfoodfast' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to postgres;" -U postgres

script:
  - coverage run  --source app/tests/v1 -m pytest -v

after_success:
  - coveralls
  - codecov --token=093aeaa3-4bb6-4d14-a60c-ae41278f9254



  